image: node:alpine

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules

stages: # List of stages for jobs, and their order of execution       
  - lint
  - jest-test
  - build

.installation:
  stage: init
  script:
    - cd ./allert-react-native && npm ci --legacy-peer-deps --cache node_modules --prefer-offline


.eslint:
 # tell eslint what stage it is
  stage: lint
  script:
    # Run eslint
    - node_modules/eslint/bin/eslint.js .

eas-build:
  stage: build
  only:
    - master
  script:
    - apk add --no-cache bash
    - npm i expo-cli
    - cd ./allert-react-native && npm ci --legacy-peer-deps --prefer-offline
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --non-interactive

.jest-tests:
  stage: jest-test
  script:
    - cd ./allert-react-native && npx jest --ci 
