image: node:alpine

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules

stages:
  - init   
  - lint
  - jest-test

installation:
  stage: init
  script:
    - cd ./src/allert-react-native && npm ci --legacy-peer-deps --cache node_modules --prefer-offline


eslint:
  stage: lint
  script:
    - cd ./src/allert-react-native
    - node_modules/eslint/bin/eslint.js .

jest-tests:
  stage: jest-test
  script:
    - cd ./src/allert-react-native
    - npx jest --ci 