image: node:alpine

stages:
  - init   
  - lint
  - jest-test

installation:
  stage: init
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  script:
    - cd ./src/allert-react-native && npm ci --legacy-peer-deps --cache .npm --prefer-offline
  artifacts:
    paths:
      - node_modules/


eslint:
  stage: lint
  needs:
    - job: installation
      artifacts: true 
  script:
    - node_modules/eslint/bin/eslint.js .

jest-tests:
  stage: jest-test
  needs:
    - job: installation
      artifacts: true  
  script:
    - npx jest --ci 