image: node:alpine

stages:
  - init   
  - lint
  - jest-test

cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - ./npm

before_script:
  - cd ./src/allert-react-native && npm ci --legacy-peer-deps --cache .npm --prefer-offline

eslint:
  stage: lint
  script:
    - node_modules/eslint/bin/eslint.js .

jest-tests:
  stage: jest-test
  script:
    - npx jest --ci 